### ISSUE TITLE
Config::YAML

### ISSUE THREAD

**Issue by Praxthisnovcht** [Praxthisnovcht/KillChat#3]
does not know how to do it: O

		if (! isset ( $this->Config::YAML [$event->getPlayer ()->getName ()] )) {
		    // $this->Config::YAML may be fals 
			$this->Config::YAML [$event->getPlayer ()->getName ()] ["kills"] = 0;
			// solution for CustomChat departure 0
			$this->Config::YAML [$event->getPlayer ()->getName ()] ["deaths"] = 0;

**Comment by Praxthisnovcht** [comment]
it should be good with the last commit xD

**Comment by xpyctum** [comment]
@Praxthisnovcht why you do use ```$this->Config::YAML``` ? Why not create ```$this->config = new Config();```...?

**Comment by Praxthisnovcht** [comment]
I try to make pluins with other config to watch his function x

**Comment by xpyctum** [comment]
See anothers plugins

**Comment by Praxthisnovcht** [comment]
yeah =)

**Comment by Flavius12** [comment]
Look KillChat code :)

**Comment by Flavius12** [comment]
There is the full usage of config :)

**Comment by Praxthisnovcht** [comment]
it lacks the support CustomaChat perfect use!

**Comment by Flavius12** [comment]
What exactly?

**Comment by Praxthisnovcht** [comment]
Chat-Format :dancer:
